name: aurora_assistant
description: A modern virtual assistant app for Gabriel

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.14.0
  firebase_auth: ^4.7.0
  cloud_firestore: ^4.8.0
  rive: ^0.12.0
  google_sign_in: ^6.1.0
  flutter_local_notifications: ^15.1.1
  intl: ^0.18.1
  flutter_tts: ^3.6.3
  speech_to_text: ^6.3.0
  googleapis: ^11.3.0
  googleapis_auth: ^1.3.0
  flutter_svg: ^2.0.7
  shared_preferences: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/images/
    - assets/sounds/